#############################################################################
# Makefile for building: qtpairs
# Generated by qmake (2.01a) (Qt 4.7.2) on: Thu Oct 13 15:57:58 2011
# Project:  qtpairs.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qtpairs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = TBlock.cpp \
		TGameBoard.cpp \
		main.cpp moc_TBlock.cpp \
		moc_TGameBoard.cpp \
		qrc_qtpairs.cpp
OBJECTS       = TBlock.o \
		TGameBoard.o \
		main.o \
		moc_TBlock.o \
		moc_TGameBoard.o \
		qrc_qtpairs.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtpairs.pro
QMAKE_TARGET  = qtpairs
DESTDIR       = 
TARGET        = qtpairs

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtpairs.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qtpairs.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtpairs.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtpairs1.0.0 || $(MKDIR) .tmp/qtpairs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtpairs1.0.0/ && $(COPY_FILE) --parents TBlock.h TGameBoard.h .tmp/qtpairs1.0.0/ && $(COPY_FILE) --parents qtpairs.qrc .tmp/qtpairs1.0.0/ && $(COPY_FILE) --parents TBlock.cpp TGameBoard.cpp main.cpp .tmp/qtpairs1.0.0/ && $(COPY_FILE) --parents translations/qtpairs_en.ts translations/qtpairs_ru.ts .tmp/qtpairs1.0.0/ && (cd `dirname .tmp/qtpairs1.0.0` && $(TAR) qtpairs1.0.0.tar qtpairs1.0.0 && $(COMPRESS) qtpairs1.0.0.tar) && $(MOVE) `dirname .tmp/qtpairs1.0.0`/qtpairs1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtpairs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TBlock.cpp moc_TGameBoard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TBlock.cpp moc_TGameBoard.cpp
moc_TBlock.cpp: TBlock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TBlock.h -o moc_TBlock.cpp

moc_TGameBoard.cpp: TGameBoard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TGameBoard.h -o moc_TGameBoard.cpp

compiler_rcc_make_all: qrc_qtpairs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtpairs.cpp
qrc_qtpairs.cpp: qtpairs.qrc \
		images/3.png \
		images/Qt.png \
		images/find.png \
		images/main.png \
		images/4.png \
		images/0.png \
		images/save.png \
		images/about.png \
		images/5.png \
		images/1.png \
		images/stat.png \
		images/new.png \
		images/6.png \
		images/2.png \
		images/exit.png \
		images/7.png \
		images/Beer/0.png \
		images/Beer/1.png \
		images/Beer/2.png \
		images/Beer/3.png \
		images/Beer/4.png \
		images/Beer/5.png \
		images/Beer/6.png \
		images/Beer/7.png \
		images/Software/0.png \
		images/Software/1.png \
		images/Software/2.png \
		images/Software/3.png \
		images/Software/4.png \
		images/Software/5.png \
		images/Software/6.png \
		images/Software/7.png \
		images/Tits/0.png \
		images/Tits/1.png \
		images/Tits/2.png \
		images/Tits/3.png \
		images/Tits/4.png \
		images/Tits/5.png \
		images/Tits/6.png \
		images/Tits/7.png \
		images/Puppets/0.png \
		images/Puppets/1.png \
		images/Puppets/2.png \
		images/Puppets/3.png \
		images/Puppets/4.png \
		images/Puppets/5.png \
		images/Puppets/6.png \
		images/Puppets/7.png
	/usr/bin/rcc -name qtpairs qtpairs.qrc -o qrc_qtpairs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

TBlock.o: TBlock.cpp TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TBlock.o TBlock.cpp

TGameBoard.o: TGameBoard.cpp TGameBoard.h \
		TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TGameBoard.o TGameBoard.cpp

main.o: main.cpp TGameBoard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_TBlock.o: moc_TBlock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TBlock.o moc_TBlock.cpp

moc_TGameBoard.o: moc_TGameBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TGameBoard.o moc_TGameBoard.cpp

qrc_qtpairs.o: qrc_qtpairs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtpairs.o qrc_qtpairs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

