#############################################################################
# Makefile for building: qt-pairs
# Generated by qmake (2.01a) (Qt 4.7.2) on: Fri Sep 23 12:24:03 2011
# Project:  qt-pairs.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qt-pairs.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = TBlock.cpp \
		TGameBoard.cpp \
		main.cpp moc_TBlock.cpp \
		moc_TGameBoard.cpp \
		qrc_qt-pairs.cpp
OBJECTS       = TBlock.o \
		TGameBoard.o \
		main.o \
		moc_TBlock.o \
		moc_TGameBoard.o \
		qrc_qt-pairs.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qt-pairs.pro
QMAKE_TARGET  = qt-pairs
DESTDIR       = 
TARGET        = qt-pairs

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-pairs.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qt-pairs.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile qt-pairs.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt-pairs1.0.0 || $(MKDIR) .tmp/qt-pairs1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt-pairs1.0.0/ && $(COPY_FILE) --parents TBlock.h TGameBoard.h .tmp/qt-pairs1.0.0/ && $(COPY_FILE) --parents qt-pairs.qrc .tmp/qt-pairs1.0.0/ && $(COPY_FILE) --parents TBlock.cpp TGameBoard.cpp main.cpp .tmp/qt-pairs1.0.0/ && $(COPY_FILE) --parents translations/qt-pairs_en.ts translations/qt-pairs_ru.ts .tmp/qt-pairs1.0.0/ && (cd `dirname .tmp/qt-pairs1.0.0` && $(TAR) qt-pairs1.0.0.tar qt-pairs1.0.0 && $(COMPRESS) qt-pairs1.0.0.tar) && $(MOVE) `dirname .tmp/qt-pairs1.0.0`/qt-pairs1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt-pairs1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TBlock.cpp moc_TGameBoard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TBlock.cpp moc_TGameBoard.cpp
moc_TBlock.cpp: TBlock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TBlock.h -o moc_TBlock.cpp

moc_TGameBoard.cpp: TGameBoard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TGameBoard.h -o moc_TGameBoard.cpp

compiler_rcc_make_all: qrc_qt-pairs.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qt-pairs.cpp
qrc_qt-pairs.cpp: qt-pairs.qrc \
		images/about.png \
		images/find.png \
		images/main.png \
		images/new.png \
		images/stat.png \
		images/0.png \
		images/exit.png \
		images/1.png \
		images/2.png \
		images/3.png \
		images/save.png \
		images/4.png \
		images/Qt.png \
		images/5.png \
		images/6.png \
		images/7.png
	/usr/bin/rcc -name qt-pairs qt-pairs.qrc -o qrc_qt-pairs.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

TBlock.o: TBlock.cpp TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TBlock.o TBlock.cpp

TGameBoard.o: TGameBoard.cpp TGameBoard.h \
		TBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TGameBoard.o TGameBoard.cpp

main.o: main.cpp TGameBoard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_TBlock.o: moc_TBlock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TBlock.o moc_TBlock.cpp

moc_TGameBoard.o: moc_TGameBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TGameBoard.o moc_TGameBoard.cpp

qrc_qt-pairs.o: qrc_qt-pairs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qt-pairs.o qrc_qt-pairs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

